global:
  bot_url: "https://example.com"
  debug: true

comms:
  telegram:
    token: "xxxxx:xxxxxx"
    channel: "-xxxx"
  slack:
    hook_url: "slack_webhook_here"
  mattermost:
    webhook_url: 'Mattermost_webhook_url'
    channel: 'test'
    bot_name: 'Bot'
  discord:
    hook_url: 'https://discordapp.com/api/webhooks/....../......'
    bot_name: 'Bot'

services:
  github:
    redirect: true
    secret: ''
    token: 'xxxxxxxx'
  bitbucket:
     token: ''
  telegram:
    hostname: 'xxxx.xxx.com'
    server_cert: ''
    port: 443
    permissions:
        admins:
            - user1
        moderators:
            - user2
    token: "xxxxxx:xxxxxx"
    plugins:
      giphy:
        apiKey: ''
      shodan:
        apiKey: 'xxxx'
stats:
  enabled: true

hooks:
  a_cool_project:
    github:
      settings:
        notify_branches:
          - master
        disabled_events:
          - ping
      send_to:
        telegram:
          enabled: false
          channels:
            - "-xxxxx"
          token: "xx:xxx"
        discord:
            enabled: false
            bot_name: 'Bot'
            webhooks:
              - 'https://discordapp.com/api/webhooks/xxxx/xxxxxxx'
        slack:
          enabled: false
          bot_name: 'Bot'
          webhooks:
            - 'https://hooks.slack.com/services/xxxx/xxxxx/xxxx'
        mattermost:
          enabled: true
          bot_name: 'Bot'
          webhooks:
            - 'https://mattermost.xxxxx.com/hooks/xxxx'

    bitbucket:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxx"
    codacy:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxx"
    patreon:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
    circleci:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
    docker:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxx"
    gitlab:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
    pagerduty:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
    scrutinizer:
      notify_branches:
        - master
      events:
        - inspection.created
        - inspection.completed
        - inspection.canceled
        - inspection.failed
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
    slack:
      token: "xxxxxx"
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
    travis:
      results:
        - Passed
        - Fixed
        - Broken
        - Failed
        - Still Failing
        - Errored
      notify_branches:
        - master
        - some-test-branch
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxx"
        slack:
          enabled: true
          hooks:
            - "https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx"
          token: "xxxxxxx"


  another-cool-project:
    github:
      settings:
        notify_branches:
          - master
      send_to:
        telegram:
          channels:
            - "-xxxxxx"
#          token: "xxxxxxx:xxxxxxx"
        slack:
          hooks:
            - "https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx"
          token: "xxxxxxx"
    travis:
      settings:
        notify_branches:
          - master
          - some-test-branch
        results:
          - Passed
          - Fixed
          - Broken
          - Failed
          - Still Failing
          - Errored
      send_to:
        telegram:
          channels:
            - "@passman_dev"
#          token: "xxxxxxx:xxxxxxx"
        slack:
          hooks:
            - "https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx"
          token: "xxxxxxx"
