global:
  bot_url: "https://xxxxxxx.xxxxxxx.com"
  debug: true

auth:
  github:
    client_id: xxxxxxx
    client_secret: xxxxxxx
    allowed_users:
      - brantje
  google:
    client_id: ''
    client_secret: ''
    allowed_users:
      - my@domain.com




comms:
  telegram:
    enabled: true
    token: "xxxxxxx:xxxxxxx"
    channel: "-xxxxxxx"
  slack:
    enabled: false
    hook_url: "slack_webhook_here"
  mattermost:
    enabled: false
    hook_url: 'Mattermost_webhook_url'
    channel: 'test'
    bot_name: 'Bot'
  discord:
    enabled: false
    hook_url: 'https://discordapp.com/api/webhooks/....../......'
    bot_name: 'Bot'

services:
  github:
    secret: ''
    token: 'xxxxxxx'
  bitbucket:
     token: ''
     secret: '88888'
  patreon:
    verification_key: '123456'
  telegram:
    hostname: 'xxxxxxx.xxxxxxx.com'
    server_cert: ''
    port: 443
    permissions:
        admins:
            - brantje
        moderators:
            - mrmaestroi
    token: "xxxxxxx:xxxxxxx"
    plugins:
      giphy:
        apiKey: ''
      shodan:
        apiKey: 'xxxxxxx'

inspector:
  enabled: true
  inspect_hooks: false
  forward_url: ''
  allowed_methods:
    - POST
    - PUT
    - GET

  verification_key: '3232'

stats:
  enabled: true

#--------------------------------------------------------------------------------------------------
hooks:
  a_cool_project:
    zabbix:
      send_to:
        telegram:
          enabled: true
    github:
      settings:
        secret: '123'
        notify_branches:
          - master
        disabled_events:
          - ping
      scripts:
        push:
          - python script.py
          - python script2.py
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
          token: "487520611:AAHK0r4ACqZOgUHF4Kkv1wUlRDWMWSGrKuQ"
        discord:
            enabled: false
            bot_name: 'Bot'
            webhooks:
              - 'https://discordapp.com/api/webhooks/xxxxxxx/xxxxxxx-xxxxxxx'
        slack:
          enabled: true
          bot_name: 'Bot'
          webhooks:
            - 'https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx'

    bitbucket:
      settings:
        secret: '13371337'
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    codacy:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    patreon:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    circleci:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    docker:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    pagerduty:
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    scrutinizer:
      settings:
        notify_branches:
          - master
        events:
          - inspection.created
          - inspection.completed
          - inspection.canceled
          - inspection.failed
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
    slack:
      token: "xxxxxxx"
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxx"
    travis:
      settings:
        results:
          - Passed
          - Fixed
          - Broken
          - Failed
          - Still Failing
          - Errored
        notify_branches:
          - master
      send_to:
        telegram:
          enabled: true
          channels:
            - "-xxxxxxx"
#        slack:
#          hooks:
#            - "https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx"
#          token: "xxxxxxx"
#s

  another-cool-project:
    github:
      settings:
        notify_branches:
          - master
      send_to:
        telegram:
          channels:
            - "-xxxxxxx"
#          token: "xxxxxxx:xxxxxxx"
        slack:
          hooks:
            - "https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx"
          token: "xxxxxxx"
    travis:
      settings:
        notify_branches:
          - master
          - brantje-patch-1
        results:
          - Passed
          - Fixed
          - Broken
          - Failed
          - Still Failing
          - Errored
      send_to:
        telegram:
          channels:
            - "@xxxxx"
#          token: "xxxxxxx:xxxxxxx"
        slack:
          hooks:
            - "https://hooks.slack.com/services/xxxxxxx/xxxxxxx/xxxxxxx"
          token: "xxxxxxx"
